### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by HAGAI123** [ivopetiz/algotrading#16]
after you fix the  requirements.txt   

but still i have problem ,

Traceback (most recent call last):
  File "c:\FOREX\CRYPTO\algotrading-master\cryptoalgotrading\cryptoalgotrading.py", line 17, in <module>
    import cryptoalgotrading.var as var
  File "c:\FOREX\CRYPTO\algotrading-master\cryptoalgotrading\cryptoalgotrading.py", line 17, in <module>
    import cryptoalgotrading.var as var
ModuleNotFoundError: No module named 'cryptoalgotrading.var'; 'cryptoalgotrading' is not a package

**Comment by ivopetiz** [comment]
Are you trying to run cryptoalgotrading.py?

**Comment by HAGAI123** [comment]
yes

**Comment by ivopetiz** [comment]
It is not supposed to work that way. I recommend you to read the tutorial on readme.md.
